version: '3.7'
services:
  quasar:
    build:
      context: ./admin
      dockerfile: Dockerfile
      target: develop-stage
    ports:
      - '8080:8080'
    volumes:
      - './admin:/app'
    networks:
      - laravel-network
    command: /bin/sh -c "yarn && quasar dev"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: laravel-api
    container_name: laravel-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - './api:/var/www/html'
    ports:
      - '8000:8000'
    networks:
      - laravel-network

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - '8888:80'
    volumes:
      - './api:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - laravel-network

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - './docker/mariadb:/var/lib/mysql'
    ports:
      - '3307:3306'
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
    ports:
      - '8181:80'
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

